### ISSUE TITLE
E2e tests

### ISSUE THREAD

**Issue by ymesika** [istio-ecosystem/wharf-multicluster-sync#19]
Use Istio's testing framework (with its preliminary support for Multi-Cluster) to conduct an e2e test.
Test should be able to run on CircleCI.

**Comment by esnible** [comment]
I know @mbanikazemi has been working on an end-to-end test.  His first version is a shell script.  Which parts of Istio's framework do you need for this item?

**Comment by ymesika** [comment]
There is a multi-cluster e2e test in Istio to test the Istio Multi-Cluster.
This task is more around building go tests, like other e2e tests in Istio, that can run within CircleCI.
