### ISSUE TITLE
Better organize the code and scripts

### ISSUE THREAD

**Issue by ymesika** [istio-ecosystem/wharf-multicluster-sync#24]
- Cleanup unnecessary files
- Simplify scripts
- Make sure documentation is updated

**Comment by ymesika** [comment]
@esnible In the tutorial several places mention cluster 3 but it seems like the tutorial is meant for 2 clusters.
Can I update and remove those mentions?

**Comment by esnible** [comment]
I have removed them.  Feel free to remove any incorrect mentions or let me know and I will do it.
