### ISSUE TITLE
Run root CA on one of the other clusters

### ISSUE THREAD

**Issue by ymesika** [istio-ecosystem/wharf-multicluster-sync#25]
Find a way to run the root CA on one of the clusters rather than its own.

**Comment by esnible** [comment]
The scripts _docs/install/demo_context.sh_ and _install_citadel.sh_ are able to set up with the root CA in one of the clusters.

To use them, do

```
source ./demo_context.sh <context-ca> <context1> <context2> [<context3>]
./install_citadel.sh
```

Make sure that context-ca matches one of the other contexts and everything will be configured correctly.

May we close this item?

**Comment by ymesika** [comment]
Tested with two clusters and it works.
